function [V,H] = Arnoldi(A,v)
%ARNOLDI Implements the Arnoldi iteration
%   Implements the Arnoldi iteration
%INPUT:
%   A = mxm simple matrix
%   v = vector of size m, with grade equal to m
%OUTPUT
%   V = orthogonal basis for polynomial Krylov subspaces generated by A and v
%   H = Hessenberg matrix representing projection V^H A V

m = length(A);

v = v(:); % make column vector
v = v/norm(v);

V = [v];
H = zeros(m+1,m);
for i=1:m
    vhat = A*V(:,i);
    for j = i:-1:1
        h = dot(V(:,j),vhat);
        vhat = vhat-h*V(:,j);
        H(j,i) = h;
    end
    H(i+1,i) = norm(vhat);
    V = [V,vhat/norm(vhat)];
end

end

